micronaut:
  application:
    name: baseline-micronaut
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

  server:
    # let system environment variable override context-path if available
    # or else just use / as root. The Dockerfile sets this to /otc matching
    # what the ECS Fargate task is routed as from the load balancer.
    context-path: ${CONTEXT_PATH:/}
    port: 8080
    cors:
      enabled: false

  security:
    enabled: true
    endpoints:
      login:
        enabled: true
  http:
    client:
      max-content-length: 104857600 # 100mb max content length
      read-timeout: 60s
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
    disk-space:
      enabled: false
jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false
  json-view:
    enabled: true

