micronaut:
  application:
    name: baseline-micronaut
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

  server:
    # let system environment variable override context-path if available
    # or else just use / as root. The Dockerfile sets this to /otc matching
    # what the ECS Fargate task is routed as from the load balancer.
    context-path: ${CONTEXT_PATH:/}
    port: 8080
    cors:
      enabled: false

  # For local development use Basic Auth for authentication
  security:
    enabled: true
    token:
      basic-auth:
        enabled: false
      jwt:
        bearer:
          enabled: true
        enabled: true
        signatures:
          jwks:
            awscognito:
              url: ${jwksUrl}
      writer:
        header:
          enabled: true
      propagation:
        enabled: true
        service-id-regex: "whoami|baseline-micronaut"

  http:
    client:
      max-content-length: 104857600 # 100mb max content length
      read-timeout: 60s
    services:
      whoami:
        url: ${baseUrl}
      baseline-micronaut:
        url: ${baseUrl}

#when doing local development and using remote services.
#baseUrl: https://services.dev.trafficinfo.vydev.io
#jwksUrl: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_t3uhWZYm9/.well-known/jwks.json

baseUrl: http://localhost:8080

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
    disk-space:
      enabled: false
jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false
    adjustDatesToContextTimeZone: false
  json-view:
    enabled: true

