micronaut:
  security:
    basic-auth:
      enabled: false

  http:
    services:
      whoami:
        url: ${baseUrl}
        health-check: true
        health-check-interval: 15s
        health-check-uri: /health
      baseline-micronaut:
        url: ${baseUrl}
        path: /baseline-micronaut