micronaut:
  # enable security when running in the cloud.
  # JWT validation, parses incoming Bearer token and validates
  # signatures and attributes against jwks.json.
  #
  # The jwksUrl property below is stored in cloud SSM as a common parameter
  # under /trafficinfo/config/application for all applications to use
  # and contain the url to the public endpoint where public keys are published
  # to verify signatures in JWT token.
  security:
    enabled: true
    token:
      basic-auth:
        enabled: false
      jwt:
        bearer:
          enabled: true
        enabled: true
        signatures:
          jwks:
            awscognito:
              url: ${jwksUrl}
      writer:
        header:
          enabled: true

      # propagate only to known services
      # the access token should be treated like normal credentials and not must not be
      # passed to unknown services that could get access to our system by the token.
      propagation:
        enabled: true
        service-id-regex: "whoami|baseline-micronaut"

  http:
    client:
      max-content-length: 104857600 # 100mb max content length
      read-timeout: 60s
    services:
      whoami:
        url: ${baseUrl}
        path: /whoami
      baseline-micronaut:
        url: ${baseUrl}
        path: /baseline-micronaut