version: 2.1
# Local parameters can be used to avoid repetitive values (referenced as `<< pipeline.parameters.parameter-name >>`)
parameters:
  s3_bucket_name:
    type: string
    default: "929368261477-pipeline-artifact"
  pipeline_name:
    type: string
    default: "trafficinfo-baseline-micronaut-state-machine"
  ecr_repo_name:
    type: string
    default: "trafficinfo-baseline-micronaut"


orbs:
  stepfunction-ci: vydev/ciorb@2.0.3
  trafficinfo: vydev/trafficinfo-orb@dev:alpha

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - trafficinfo/build-and-deploy:
          context: trafficinfo
          envs: "service, test, stage, prod"
          ecr_repo_name: << pipeline.parameters.ecr_repo_name >>
          s3_bucket_name: << pipeline.parameters.s3_bucket_name >>
          pipeline_name: << pipeline.parameters.pipeline_name >>
