version: 2.1
parameters:
  ecr_repo_name:
    type: string
    default: "trafficinfo-baseline-micronaut"

  application_name:
    type: string
    default: "trafficinfo-baseline-micronaut"

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  deployment: vydev/deployment@0.3.7
  gradle: circleci/gradle@3.0.0
  terraform: circleci/terraform@3.2.1

jobs:
  build-and-upload-service:
    executor: aws-ecr/default
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          attach-workspace: true
          repo: << pipeline.parameters.ecr_repo_name >>
          dockerfile: "Docker/Dockerfile"
          tag: "latest,${CIRCLE_BRANCH}-branch,${CIRCLE_SHA1:0:7}-SHA1"

executors:
  ubuntu:
    working_directory: ~/tmp_checkout
    machine:
      image: ubuntu-2204:2023.04.2

workflows:
  do:
    jobs:
      - gradle/test:
          name: "Build and test"
          executor: ubuntu
          context:
            - ruteplan
            - nexus
          deps_checksum_file: build.gradle.kts
          test_command: "clean test build --no-daemon"
          post-steps:
            - run:
                command: ./gradlew -q javaToolchains
                when: on_fail
            - run: ls -laR build/docker
            - persist_to_workspace:
                root: .
                paths:
                  - "build/*"

      - build-and-upload-service:
          context: ruteplan
          requires:
            - "Build and test"

      - deployment/trigger-deployment:
          context:
            - ruteplan
          requires:
            - build-and-upload-service
# STOPSHIP set branch filter to master before merge
#          filters:
#            branches:
#              only: [ master ]