version: 2.1
# Local parameters can be used to avoid repetitive values (referenced as `<< pipeline.parameters.parameter-name >>`)
parameters:
  s3_bucket_name:
    type: string
    default: "929368261477-pipeline-artifact"
  pipeline_name:
    type: string
    default: "trafficinfo-baseline-micronaut-state-machine"
  ecr_repo_name:
    type: string
    default: "trafficinfo-baseline-micronaut"


orbs:
  stepfunction-ci: vydev/ciorb@2.2.0
  trafficinfo: vydev/trafficinfo-orb@0.2.1
  sdkman: joshdholtz/sdkman@0.2.0

jobs:
  # This job is only temporarily used until
  # a better way of installing Eclipse Temurin has been found.
  install-sdkman:
    docker:
      - image: cimg/base:2021.02
    steps:
      - run: curl -s "https://get.sdkman.io" | bash
      - run: source "$HOME/.sdkman/bin/sdkman-init.sh"
      - run: sdk version

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - trafficinfo/build:
          context:
            - trafficinfo
            - nexus
          jdk_version: "17"
          pre-steps:
            - run: curl -s "https://get.sdkman.io" | bash
            - run: source "$HOME/.sdkman/bin/sdkman-init.sh"
            - run: sdk version
          post-steps:
            - trafficinfo/slack-failure

      - stepfunction-ci/build-docker:
          context: trafficinfo
          enable_buildkit: true
          ecr_repo_name: << pipeline.parameters.ecr_repo_name >>
          requires:
            - trafficinfo/build
          post-steps:
            - trafficinfo/slack-failure

      - stepfunction-ci/validate-terraform:
          context: trafficinfo
          terraformimage: vydev/terraform:1.0.0
          envs: "test, stage, prod"
          post-steps:
            - trafficinfo/slack-failure

      - stepfunction-ci/build-repo-zip:
          context: trafficinfo
          s3_bucket_name: << pipeline.parameters.s3_bucket_name >>
          filters:
            branches:
              only: master
          requires:
            - trafficinfo/build

          post-steps:
            - trafficinfo/slack-failure

      - stepfunction-ci/upload-artifacts:
          context: trafficinfo
          s3_bucket_name: << pipeline.parameters.s3_bucket_name >>
          filters:
            branches:
              only: master
          requires:
            - stepfunction-ci/build-repo-zip
          post-steps:
            - trafficinfo/slack-failure

      - stepfunction-ci/upload-trigger-event:
          context: trafficinfo
          s3_bucket_name: << pipeline.parameters.s3_bucket_name >>
          pipeline_name: << pipeline.parameters.pipeline_name >>
          filters:
            branches:
              only: master
          requires:
            - stepfunction-ci/build-docker
            - stepfunction-ci/upload-artifacts
          post-steps:
            - trafficinfo/slack-failure

      - trafficinfo/slack-notify-success:
          context: trafficinfo
          message: ":sunglasses: :thumbsup: Uploaded pipeline trigger event for $CIRCLE_PROJECT_REPONAME version $CIRCLE_SHA1."
          requires:
            - stepfunction-ci/upload-trigger-event
