version: 2.1
# Local parameters can be used to avoid repetitive values (referenced as `<< pipeline.parameters.parameter-name >>`)
parameters:
  s3_bucket_name:
    type: string
    default: "929368261477-pipeline-artifact"
  pipeline_name:
    type: string
    default: "trafficinfo-baseline-micronaut-state-machine"
  ecr_repo_name:
    type: string
    default: "trafficinfo-baseline-micronaut"
  deployment_repo:
    type: string
    default: "trafficinfo-baseline-terraform"

orbs:
  stepfunction-ci: vydev/ciorb@2.2.0
  trafficinfo: vydev/trafficinfo-orb@0.2.1
  gradle: circleci/gradle@3.0.0

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - trafficinfo/build:
          context:
            - trafficinfo
            - nexus
          jdk_version: "17"
          post-steps:
            - trafficinfo/slack-failure
            - run: ./gradlew -q javaToolchains

      - stepfunction-ci/build-docker:
          context: trafficinfo
          enable_buildkit: true
          ecr_repo_name: << pipeline.parameters.ecr_repo_name >>
          requires:
            - trafficinfo/build
          post-steps:
            - trafficinfo/slack-failure

      - stepfunction-ci/build-repo-zip:
          context: trafficinfo
          s3_bucket_name: << pipeline.parameters.s3_bucket_name >>
          requires:
            - trafficinfo/build

          post-steps:
            - trafficinfo/slack-failure

      - stepfunction-ci/upload-artifacts:
          context: trafficinfo
          s3_bucket_name: << pipeline.parameters.s3_bucket_name >>
          requires:
            - stepfunction-ci/build-repo-zip
          post-steps:
            - trafficinfo/slack-failure

      - stepfunction-ci/upload-trigger-event:
          context: trafficinfo
          s3_bucket_name: << pipeline.parameters.s3_bucket_name >>
          pipeline_name: << pipeline.parameters.pipeline_name >>
          deployment_repo: << pipeline.parameters.deployment_repo >>
          requires:
            - stepfunction-ci/build-docker
            - stepfunction-ci/upload-artifacts
          post-steps:
            - trafficinfo/slack-failure

      - trafficinfo/slack-notify-success:
          context: trafficinfo
          message: ":sunglasses: :thumbsup: Uploaded pipeline trigger event for $CIRCLE_PROJECT_REPONAME version $CIRCLE_SHA1."
          requires:
            - stepfunction-ci/upload-trigger-event