version: 2.1
orbs:
  trafficinfo: vydev/trafficinfo-orb@dev:alpha

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - trafficinfo/build-and-deploy:
          context: trafficinfo
          envs: "service, test, stage, prod"
          ecr_repo_name: "trafficinfo-baseline-micronaut"
          ecr_endpoint: "929368261477.dkr.ecr.eu-west-1.amazonaws.com"
          s3_bucket_name: "929368261477-pipeline-artifact"
          pipeline_name: "trafficinfo-baseline-micronaut-state-machine"
          gradle_version: "6.7"
          terraform_version: "0.12.24"
          jdk_version: 15

# trigger